# Generated by Django 4.2.7 on 2023-11-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aunthor',
            new_name='author',
        ),
    ]
